name: Track Manuscript Progress

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track-progress:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for accurate tracking
        token: ${{ github.token }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy pandas python-dateutil
        
    - name: Install texcount
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-extra-utils
    
    - name: Count words and update progress
      run: |
        python .github/scripts/track_progress.py
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f README.md progress_plot.png .progress-data/progress.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update progress tracking [skip ci]" && git push)