name: Track Manuscript Progress (Fast)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track-progress:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ github.token }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies (cached)
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy pandas python-dateutil
    
    - name: Install minimal texcount
      run: |
        # Download texcount directly without full texlive
        wget -q https://app.uio.no/ifi/texcount/download.php?file=texcount_3_2_0_41.zip -O texcount.zip
        unzip -q texcount.zip
        chmod +x texcount.pl
        sudo mv texcount.pl /usr/local/bin/texcount
        # Install minimal perl dependencies
        sudo apt-get update -qq && sudo apt-get install -y perl
    
    - name: Count words and update progress
      run: |
        python .github/scripts/track_progress.py
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f README.md progress_plot.png .progress-data/progress.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update progress tracking [skip ci]" && git push)